obj-$(CONFIG_TOUCHSCREEN_GSL2133)	+= gslX68X.o gsl_point_id.o

$(warning  echo  local path  $(srctree)/$(obj)/gsl_point_id    $(obj)/gsl_point_id.o )
$(obj)/gsl_point_id.o: $(srctree)/$(obj)/gsl_point_id
	cp $(srctree)/$(obj)/gsl_point_id $(obj)/gsl_point_id.o

